<?php

return [
    [
        'title' => 'Dashboard',
        'icon' => 'fas fa-tachometer-alt',
        'route' => 'dashboard',
        'permission' => 'view_dashboard',
        'active' => 'dashboard',
    ],
    [
        'title' => 'Pengguna & Akses',
        'icon' => 'fas fa-users-cog',
        'permission' => ['manage_users', 'manage_roles', 'manage_permissions'],
        'active' => ['users.*', 'roles.*', 'permissions.*'],
        'children' => [
            [
                'title' => 'Users',
                'icon' => 'fas fa-users',
                'route' => 'users.index',
                'permission' => 'manage_users',
                'active' => 'users.*',
            ],
            [
                'title' => 'Roles',
                'icon' => 'fas fa-user-shield',
                'route' => 'roles.index',
                'permission' => 'manage_roles',
                'active' => 'roles.*',
            ],
            [
                'title' => 'Permissions',
                'icon' => 'fas fa-key',
                'route' => 'permissions.index',
                'permission' => 'manage_permissions',
                'active' => 'permissions.*',
            ],
        ],
    ],
    [
        'title' => 'Organisasi',
        'icon' => 'fas fa-building',
        'permission' => ['manage_organization_types', 'manage_organization_units'],
        'active' => ['organization-types.*', 'organization-units.*'],
        'children' => [
            [
                'title' => 'Tipe Organisasi',
                'icon' => 'fas fa-sitemap',
                'route' => 'organization-types.index',
                'permission' => 'manage_organization_types',
                'active' => 'organization-types.*',
            ],
            [
                'title' => 'Unit Organisasi',
                'icon' => 'fas fa-diagram-project',
                'route' => 'organization-units.index',
                'permission' => 'manage_organization_units',
                'active' => 'organization-units.*',
            ],
        ],
    ],
    [
        'title' => 'Tarif Umum',
        'icon' => 'fas fa-project-diagram',
        'permission' => ['manage_clinical_pathway', 'manage_services', 'manage_medications'],
        'active' => ['diagnoses.*', 'service-prices.*', 'medication-prices.*'],
        'children' => [
            [
                'title' => 'Daftar Tarif Umum',
                'icon' => 'fas fa-list',
                'route' => 'diagnoses.index',
                'permission' => 'manage_clinical_pathway',
                'active' => 'diagnoses.*',
            ],
            [
                'title' => 'Tarif Layanan Medis',
                'icon' => 'fas fa-money-bill-wave',
                'route' => 'service-prices.index',
                'permission' => 'manage_services',
                'active' => 'service-prices.*',
            ],
            [
                'title' => 'Tarif & Harga Obat',
                'icon' => 'fas fa-money-bill-wave',
                'route' => 'medication-prices.index',
                'permission' => 'manage_medications',
                'active' => 'medication-prices.*',
            ],
        ],
    ],
    [
        'title' => 'Unit Cost',
        'icon' => 'fas fa-calculator',
        'permission' => 'view_unit_cost',
        'active' => ['unit-cost.*', 'unit-cost-service-prices.*', 'unit-cost-medication-prices.*'],
        'children' => [
            [
                'title' => 'Simulasi Unit Cost',
                'icon' => 'fas fa-chart-line',
                'route' => 'unit-cost.index',
                'permission' => 'view_unit_cost',
                'active' => 'unit-cost.*',
            ],
            [
                'title' => 'Tarif Layanan Medis',
                'icon' => 'fas fa-money-bill-wave',
                'route' => 'unit-cost-service-prices.index',
                'permission' => 'view_unit_cost',
                'active' => 'unit-cost-service-prices.*',
            ],
            [
                'title' => 'Tarif & Harga Obat',
                'icon' => 'fas fa-money-bill-wave',
                'route' => 'unit-cost-medication-prices.index',
                'permission' => 'view_unit_cost',
                'active' => 'unit-cost-medication-prices.*',
            ],
        ],
    ],
    [
        'title' => 'Master Data',
        'icon' => 'fas fa-database',
        'permission' => ['manage_service_groups', 'manage_services', 'manage_medications'],
        'active' => ['service-groups.*', 'services.*', 'medications.*', 'medication-groups.*', 'medication-commodities.*', 'medication-product-groups.*'],
        'children' => [
            [
                'title' => 'Golongan Layanan',
                'icon' => 'fas fa-tags',
                'route' => 'service-groups.index',
                'permission' => 'manage_service_groups',
                'active' => 'service-groups.*',
            ],
            [
                'title' => 'Layanan Medis',
                'icon' => 'fas fa-stethoscope',
                'route' => 'services.index',
                'permission' => 'manage_services',
                'active' => 'services.*',
            ],
            [
                'title' => 'Obat & Alkes',
                'icon' => 'fas fa-pills',
                'route' => 'medications.index',
                'permission' => 'manage_medications',
                'active' => 'medications.*',
            ],
            [
                'title' => 'Golongan Obat',
                'icon' => 'fas fa-layer-group',
                'route' => 'medication-groups.index',
                'permission' => 'manage_medications',
                'active' => 'medication-groups.*',
            ],
            [
                'title' => 'Komoditi Obat',
                'icon' => 'fas fa-boxes',
                'route' => 'medication-commodities.index',
                'permission' => 'manage_medications',
                'active' => 'medication-commodities.*',
            ],
            [
                'title' => 'Kelompok Barang',
                'icon' => 'fas fa-tags',
                'route' => 'medication-product-groups.index',
                'permission' => 'manage_medications',
                'active' => 'medication-product-groups.*',
            ],
        ],
    ],
];
